### ISSUE TITLE
не запускается...

### ISSUE THREAD

**Issue by BoyNG** [kazqvaizer/litera#5]
выдаёт 
C:\litera-master\starter.py:5: DeprecationWarning: The parser module is deprecated and will be removed in future versions of Python
  from parser import LitEraParser
Traceback (most recent call last):
  File "C:\litera-master\starter.py", line 5, in <module>
    from parser import LitEraParser
ImportError: cannot import name 'LitEraParser' from 'parser' (unknown location)

**Comment by kazqvaizer** [comment]
Самый простой способ - прокинуть текущую директорию в переменную окружения PYTHONPATH. Возможно, что вы пытаетесь запустить скрипт с помощью системного python, хотя установили virtualenv или наоборот.
